//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Zulu.BusinessService.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Address))]
    [KnownType(typeof(Warehouse))]
    public partial class Distributor: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int DistributorID
        {
            get { return _distributorID; }
            set
            {
                if (_distributorID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'DistributorID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _distributorID = value;
                    OnPropertyChanged("DistributorID");
                }
            }
        }
        private int _distributorID;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        [DataMember]
        public Nullable<int> DistributorTypeID
        {
            get { return _distributorTypeID; }
            set
            {
                if (_distributorTypeID != value)
                {
                    _distributorTypeID = value;
                    OnPropertyChanged("DistributorTypeID");
                }
            }
        }
        private Nullable<int> _distributorTypeID;
    
        [DataMember]
        public Nullable<int> AddressID
        {
            get { return _addressID; }
            set
            {
                if (_addressID != value)
                {
                    ChangeTracker.RecordOriginalValue("AddressID", _addressID);
                    if (!IsDeserializing)
                    {
                        if (npAddress != null && npAddress.AddressID != value)
                        {
                            npAddress = null;
                        }
                    }
                    _addressID = value;
                    OnPropertyChanged("AddressID");
                }
            }
        }
        private Nullable<int> _addressID;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Address npAddress
        {
            get { return _npAddress; }
            set
            {
                if (!ReferenceEquals(_npAddress, value))
                {
                    var previousValue = _npAddress;
                    _npAddress = value;
                    FixupnpAddress(previousValue);
                    OnNavigationPropertyChanged("npAddress");
                }
            }
        }
        private Address _npAddress;
    
        [DataMember]
        public TrackableCollection<Warehouse> npWarehouse
        {
            get
            {
                if (_npWarehouse == null)
                {
                    _npWarehouse = new TrackableCollection<Warehouse>();
                    _npWarehouse.CollectionChanged += FixupnpWarehouse;
                }
                return _npWarehouse;
            }
            set
            {
                if (!ReferenceEquals(_npWarehouse, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_npWarehouse != null)
                    {
                        _npWarehouse.CollectionChanged -= FixupnpWarehouse;
                    }
                    _npWarehouse = value;
                    if (_npWarehouse != null)
                    {
                        _npWarehouse.CollectionChanged += FixupnpWarehouse;
                    }
                    OnNavigationPropertyChanged("npWarehouse");
                }
            }
        }
        private TrackableCollection<Warehouse> _npWarehouse;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            npAddress = null;
            npWarehouse.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupnpAddress(Address previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.npDistributor.Contains(this))
            {
                previousValue.npDistributor.Remove(this);
            }
    
            if (npAddress != null)
            {
                if (!npAddress.npDistributor.Contains(this))
                {
                    npAddress.npDistributor.Add(this);
                }
    
                AddressID = npAddress.AddressID;
            }
            else if (!skipKeys)
            {
                AddressID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("npAddress")
                    && (ChangeTracker.OriginalValues["npAddress"] == npAddress))
                {
                    ChangeTracker.OriginalValues.Remove("npAddress");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("npAddress", previousValue);
                }
                if (npAddress != null && !npAddress.ChangeTracker.ChangeTrackingEnabled)
                {
                    npAddress.StartTracking();
                }
            }
        }
    
        private void FixupnpWarehouse(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Warehouse item in e.NewItems)
                {
                    item.npDistributor = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("npWarehouse", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Warehouse item in e.OldItems)
                {
                    if (ReferenceEquals(item.npDistributor, this))
                    {
                        item.npDistributor = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("npWarehouse", item);
                    }
                }
            }
        }

        #endregion
    }
}
