//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Zulu.BusinessService.Data
{
    [DataContract(IsReference = true)]
    public partial class StockAllocation: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int StockAllocationID
        {
            get { return _stockAllocationID; }
            set
            {
                if (_stockAllocationID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'StockAllocationID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _stockAllocationID = value;
                    OnPropertyChanged("StockAllocationID");
                }
            }
        }
        private int _stockAllocationID;
    
        [DataMember]
        public Nullable<int> ProductVariantID
        {
            get { return _productVariantID; }
            set
            {
                if (_productVariantID != value)
                {
                    _productVariantID = value;
                    OnPropertyChanged("ProductVariantID");
                }
            }
        }
        private Nullable<int> _productVariantID;
    
        [DataMember]
        public Nullable<int> FromWarehouseID
        {
            get { return _fromWarehouseID; }
            set
            {
                if (_fromWarehouseID != value)
                {
                    _fromWarehouseID = value;
                    OnPropertyChanged("FromWarehouseID");
                }
            }
        }
        private Nullable<int> _fromWarehouseID;
    
        [DataMember]
        public Nullable<int> ToWarehouseID
        {
            get { return _toWarehouseID; }
            set
            {
                if (_toWarehouseID != value)
                {
                    _toWarehouseID = value;
                    OnPropertyChanged("ToWarehouseID");
                }
            }
        }
        private Nullable<int> _toWarehouseID;
    
        [DataMember]
        public Nullable<int> PurchaseID
        {
            get { return _purchaseID; }
            set
            {
                if (_purchaseID != value)
                {
                    _purchaseID = value;
                    OnPropertyChanged("PurchaseID");
                }
            }
        }
        private Nullable<int> _purchaseID;
    
        [DataMember]
        public Nullable<int> Quantity
        {
            get { return _quantity; }
            set
            {
                if (_quantity != value)
                {
                    _quantity = value;
                    OnPropertyChanged("Quantity");
                }
            }
        }
        private Nullable<int> _quantity;
    
        [DataMember]
        public Nullable<int> StockAllocationStatus
        {
            get { return _stockAllocationStatus; }
            set
            {
                if (_stockAllocationStatus != value)
                {
                    _stockAllocationStatus = value;
                    OnPropertyChanged("StockAllocationStatus");
                }
            }
        }
        private Nullable<int> _stockAllocationStatus;
    
        [DataMember]
        public Nullable<System.DateTime> CreatedOn
        {
            get { return _createdOn; }
            set
            {
                if (_createdOn != value)
                {
                    _createdOn = value;
                    OnPropertyChanged("CreatedOn");
                }
            }
        }
        private Nullable<System.DateTime> _createdOn;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion
    }
}
